"""Exact identities for a causal one-delay reset protocol.

The protocol belongs to the unprepared two-module FitzHugh--Nagumo RFDE.
During the final holding interval the voltage is clamped at a constant
modal setpoint while the recovery variables obey their physical equations.
The terminal collective recovery is prescribed and the transverse recovery
is placed at its forced equilibrium.  A hold lasting at least the largest
physical delay then overwrites every delayed voltage value used after
release.

This module certifies the reset-history identities and a quantitative scalar
root-transfer lemma.  It does not prove that the positive-epsilon reset
family has a unique pulse/quiet separator; that is the model-specific
exchange problem isolated in the accompanying Paper III note.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import exp
from typing import Iterable

import sympy as sp

from .final_two_module import final_two_module_audit


@dataclass(frozen=True)
class CausalResetAudit:
    """Exact model and history identities of the final holding phase."""

    delta: sp.Symbol
    epsilon: sp.Expr
    scaled_history_time: sp.Symbol
    unfolding: sp.Symbol
    critical_setpoint: sp.Symbol
    transverse_setpoint: sp.Symbol
    terminal_collective_recovery: sp.Symbol
    recovery_gap: sp.Symbol
    reset_voltage: sp.Matrix
    reset_recovery_endpoint: sp.Matrix
    scaled_reset_history: sp.Matrix
    reset_modal_endpoint: sp.Matrix
    reset_parameter_jacobian: sp.Matrix
    reset_parameter_rank: int
    constant_voltage_delay_residual: sp.Matrix
    recovery_history_residual: sp.Matrix
    history_endpoint_residual: sp.Matrix
    release_critical_fast_field: sp.Expr
    release_transverse_fast_field: sp.Expr
    critical_recovery_injection: sp.Expr
    transverse_recovery_injection: sp.Expr


def causal_reset_audit() -> CausalResetAudit:
    r"""Return exact identities for the voltage-hold/recovery-preset reset.

    Let ``vartheta=delta*t`` on the fixed history interval
    ``[-theta_*,0]``.  For constant voltage modal coordinates ``(xi,zeta)``
    and prescribed terminal collective recovery ``rho``, the reset history
    is

    .. math::
       v_R=v_*+r\xi+q\zeta,

    .. math::
       w_R(\vartheta)=w_*+
       r[\rho+\delta(\xi-\mu)\vartheta]
       +q\frac{\delta^2\zeta}{D_w}.

    It is generated by the physical recovery equation while voltage is
    clamped.  Since ``B=C_0^eta+C_1^eta``, the released delayed feedback is
    exactly zero at the constant voltage history, for every admissible
    redistribution ``eta``.
    """

    base = final_two_module_audit()
    delta = sp.Symbol("delta", positive=True)
    epsilon = delta**2
    vartheta = sp.Symbol("vartheta", real=True)
    mu, xi, zeta, rho = sp.symbols(
        "mu xi_R zeta_R rho_R", real=True
    )
    recovery_gap = sp.Symbol("D_w", positive=True)
    eta = sp.Symbol("eta", real=True)

    r = sp.Matrix(base.critical_right)
    q = sp.Matrix(base.transverse_right)
    ell = sp.Matrix(base.critical_left)
    m = sp.Matrix(base.transverse_left)
    v_star = sp.Matrix(base.equilibrium_v)
    w_star = sp.Matrix(base.equilibrium_w)

    reset_voltage = sp.simplify(v_star + r * xi + q * zeta)
    transverse_recovery = epsilon * zeta / recovery_gap
    reset_recovery_endpoint = sp.simplify(
        w_star + r * rho + q * transverse_recovery
    )
    history_recovery = sp.simplify(
        w_star
        + r * (rho + delta * (xi - mu) * vartheta)
        + q * transverse_recovery
    )
    scaled_reset_history = sp.Matrix.vstack(
        reset_voltage, history_recovery
    )

    layer_0 = sp.Matrix(base.perturbed_layer_0).subs(base.eta, eta)
    layer_1 = sp.Matrix(base.perturbed_layer_1).subs(base.eta, eta)
    total_gain = sp.Matrix(base.total_gain)
    constant_voltage_delay_residual = sp.simplify(
        total_gain * reset_voltage
        - layer_0 * reset_voltage
        - layer_1 * reset_voltage
    )

    projector = sp.Matrix(base.transverse_projector)
    slow_source = sp.Matrix(
        [
            reset_voltage[0] - base.sigma - mu,
            reset_voltage[1] - 2 * mu,
        ]
    )
    recovery_rhs = sp.simplify(
        epsilon * slow_source
        - recovery_gap * projector * (history_recovery - w_star)
    )
    # Since vartheta=delta*t, physical differentiation is delta*d/dvartheta.
    recovery_history_residual = sp.simplify(
        delta * sp.diff(history_recovery, vartheta) - recovery_rhs
    )
    history_endpoint_residual = sp.simplify(
        history_recovery.subs(vartheta, 0) - reset_recovery_endpoint
    )

    reset_modal_endpoint = sp.Matrix(
        [
            (ell.T * (reset_voltage - v_star))[0],
            (m.T * (reset_voltage - v_star))[0],
            (ell.T * (reset_recovery_endpoint - w_star))[0],
            (m.T * (reset_recovery_endpoint - w_star))[0],
        ]
    ).applyfunc(sp.simplify)
    reset_parameter_jacobian = sp.simplify(
        reset_modal_endpoint.jacobian((xi, zeta, rho))
    )
    reset_parameter_rank = int(reset_parameter_jacobian.rank())

    v_1, v_2 = reset_voltage
    w_1, w_2 = reset_recovery_endpoint
    local_fast_field = sp.Matrix(
        [
            v_1
            - v_1**3 / 3
            - w_1
            + (v_2 - v_1) / 2,
            v_2
            - v_2**3 / 3
            - w_2
            + 2 * (v_1 - v_2),
        ]
    )
    release_critical_fast_field = sp.factor(
        (ell.T * local_fast_field)[0]
    )
    release_transverse_fast_field = sp.factor(
        (m.T * local_fast_field)[0]
    )

    return CausalResetAudit(
        delta=delta,
        epsilon=epsilon,
        scaled_history_time=vartheta,
        unfolding=mu,
        critical_setpoint=xi,
        transverse_setpoint=zeta,
        terminal_collective_recovery=rho,
        recovery_gap=recovery_gap,
        reset_voltage=reset_voltage,
        reset_recovery_endpoint=reset_recovery_endpoint,
        scaled_reset_history=scaled_reset_history,
        reset_modal_endpoint=reset_modal_endpoint,
        reset_parameter_jacobian=reset_parameter_jacobian,
        reset_parameter_rank=reset_parameter_rank,
        constant_voltage_delay_residual=constant_voltage_delay_residual,
        recovery_history_residual=recovery_history_residual,
        history_endpoint_residual=history_endpoint_residual,
        release_critical_fast_field=release_critical_fast_field,
        release_transverse_fast_field=release_transverse_fast_field,
        critical_recovery_injection=sp.simplify(
            sp.diff(release_critical_fast_field, rho)
        ),
        transverse_recovery_injection=sp.simplify(
            sp.diff(release_transverse_fast_field, rho)
        ),
    )


def maximal_physical_delay(
    delta: float,
    scaled_delays: Iterable[float],
) -> float:
    """Return ``max(theta_k)/delta`` after checking the delay data."""

    if delta <= 0.0:
        raise ValueError("delta must be positive")
    delays = tuple(float(value) for value in scaled_delays)
    if not delays:
        raise ValueError("at least one scaled delay is required")
    if any(value < 0.0 for value in delays):
        raise ValueError("scaled delays must be nonnegative")
    return max(delays) / delta


def reset_memory_margin(
    hold_duration: float,
    *,
    delta: float,
    scaled_delays: Iterable[float],
) -> float:
    """Return time beyond the one-maximal-delay erasure requirement.

    A nonnegative value means that every delayed voltage argument queried at
    or after release lies in either the declared hold interval or the
    post-release solution.  A negative value exposes pre-hold voltage memory.
    """

    if hold_duration < 0.0:
        raise ValueError("hold_duration must be nonnegative")
    return hold_duration - maximal_physical_delay(delta, scaled_delays)


def recovery_endpoint_error(
    hold_duration: float,
    *,
    recovery_gap: float,
    initial_collective_error: float,
    initial_transverse_error: float,
) -> tuple[float, float]:
    r"""Propagate recovery-preparation errors through a voltage hold.

    For two holds with the same clamped voltage, the modal error equations
    are exactly ``dot(Delta rho)=0`` and
    ``dot(Delta kappa)=-D_w Delta kappa``.  The collective error therefore
    survives unchanged; only the transverse error is washed out.
    """

    if hold_duration < 0.0:
        raise ValueError("hold_duration must be nonnegative")
    if recovery_gap <= 0.0:
        raise ValueError("recovery_gap must be positive")
    return (
        float(initial_collective_error),
        float(initial_transverse_error) * exp(-recovery_gap * hold_duration),
    )


@dataclass(frozen=True)
class SimpleRootTransferCertificate:
    """Quantitative data for the scalar perturbation root lemma."""

    derivative_margin: float
    shift_bound: float
    interval_radius: float
    is_contained: bool


def simple_root_transfer_certificate(
    *,
    gap_slope_lower: float,
    perturbation_derivative_upper: float,
    perturbation_at_gap_root: float,
    interval_radius: float,
) -> SimpleRootTransferCertificate:
    r"""Audit the hypotheses and bound of a simple-root transfer.

    If ``d(mu_c)=0``, ``d'`` has fixed sign and magnitude at least ``m``,
    and ``g=d+e`` with ``||e'||<=q<m``, then any transferred root obeys

    ``|mu_R-mu_c| <= |e(mu_c)|/(m-q)``.

    If that bound is strictly smaller than the available interval radius,
    endpoint signs and monotonicity also give existence and uniqueness.
    """

    if gap_slope_lower <= 0.0:
        raise ValueError("gap_slope_lower must be positive")
    if perturbation_derivative_upper < 0.0:
        raise ValueError(
            "perturbation_derivative_upper must be nonnegative"
        )
    if perturbation_derivative_upper >= gap_slope_lower:
        raise ValueError("the perturbation derivative must be smaller")
    if interval_radius <= 0.0:
        raise ValueError("interval_radius must be positive")

    margin = gap_slope_lower - perturbation_derivative_upper
    shift = abs(float(perturbation_at_gap_root)) / margin
    return SimpleRootTransferCertificate(
        derivative_margin=margin,
        shift_bound=shift,
        interval_radius=float(interval_radius),
        is_contained=shift < interval_radius,
    )
