"""Exact terminal-history theorem for the finite leaky-FHN pulse.

The physical pulse is applied to the voltage equation on ``0 <= t <= 1``
from the quiet equilibrium history.  Both declared delays exceed one, so
every delayed slot seen during the pulse is the equilibrium.  The terminal
history at ``t=1`` is therefore generated by a smooth two-dimensional
parameter ODE, although it is an element of the RFDE phase space
``C([-tau_1,0], R^2)``.

This module records the exact reduction and a sign theorem for the true
stimulus variation.  It proves that the terminal-history curve is an
oriented C1 embedding.  It does *not* construct the inner periodic orbit's
stable manifold, pair its defining covector with the terminal-history
tangent, prove a threshold, or route either side to an attractor.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, fields
from fractions import Fraction
from functools import lru_cache
from hashlib import sha256
import json
from pathlib import Path
import platform
from typing import Any, Mapping

import sympy as sp

from canard_control.autonomous_leaky_recovery_bistable import (
    EPSILON,
    KAPPA_1,
    KAPPA_3,
    UNFOLDING,
)


MODEL_ID = "autonomous-leaky-recovery-physical-pulse-terminal-history"
AUDIT_ID = "leaky-pulse-terminal-history-exact-orientation-v1"

PULSE_DURATION = Fraction(1)
PULSE_LEFT = Fraction(3, 10)
PULSE_RIGHT = Fraction(8, 25)
DELAY_MULTIPLIERS = (4, 5)

PROOF_SOURCE_RELATIVE_PATH = (
    "src/canard_control/leaky_pulse_terminal_history.py"
)
PARENT_SOURCE_RELATIVE_PATH = (
    "src/canard_control/autonomous_leaky_recovery_bistable.py"
)
PARENT_PROBE_RELATIVE_PATH = (
    "experiments/autonomous_leaky_recovery_bistable_probe.py"
)
GENERATOR_RELATIVE_PATH = "experiments/leaky_pulse_terminal_history.py"
RESULT_RELATIVE_PATH = (
    "experiments/results/leaky_pulse_terminal_history.json"
)
NOTE_RELATIVE_PATH = "docs/leaky-pulse-terminal-history.md"
DEFAULT_COMMAND = (
    "PYTHONPATH=src /usr/bin/python3 "
    "experiments/leaky_pulse_terminal_history.py"
)
MANIFEST_ARITHMETIC = (
    "exact rational and SymPy algebra; exact comparison 4*sqrt(5)>1; "
    "first-zero and Gronwall sign argument for the stimulus variation; "
    "no orbit, Floquet, stable-manifold, basin-routing, onset, or control-"
    "inverse validation"
)


EXACT_TRUE_FLAGS = (
    "both_delays_strictly_exceed_pulse_duration_proved",
    "pulse_interval_rfde_reduces_to_parameter_ode_proved",
    "terminal_history_map_jointly_c1_proved",
    "exact_stimulus_variational_system_proved",
    "stimulus_voltage_variation_strictly_positive_proved",
    "stimulus_recovery_variation_strictly_positive_proved",
    "terminal_history_curve_injective_proved",
    "terminal_history_curve_oriented_c1_embedding_proved",
    "componentwise_terminal_history_ordering_proved",
)

OPEN_FALSE_FLAGS = (
    "inner_periodic_orbit_stable_manifold_validated",
    "stable_manifold_defining_covector_validated",
    "stable_covector_terminal_tangent_pairing_nonzero_validated",
    "history_space_separator_and_routing_validated",
    "endpoint_basin_inclusions_validated",
    "unique_physical_pulse_onset_validated",
    "canard_root_equals_physical_onset_proved",
)


@dataclass(frozen=True)
class PulseTerminalHistoryCertificate:
    """Serializable statement and strict claim boundary."""

    model_id: str
    audit_id: str
    history_space: str
    epsilon: str
    unfolding_a: str
    kappa_1: str
    kappa_3: str
    pulse_interval: tuple[str, str]
    declared_pulse_amplitude_interval: tuple[str, str]
    physical_delays: tuple[str, str]
    delayed_slot_during_pulse: str
    reduced_fast_equation: str
    reduced_slow_equation: str
    voltage_stimulus_variation_equation: str
    recovery_stimulus_variation_equation: str
    current_variational_coefficient: str
    voltage_variation_upper_bound: str
    recovery_variation_upper_bound: str
    first_zero_derivative_lower_bound: str
    terminal_history_derivative: str
    exact_scope: str
    remaining_transversality: str
    both_delays_strictly_exceed_pulse_duration_proved: bool
    pulse_interval_rfde_reduces_to_parameter_ode_proved: bool
    terminal_history_map_jointly_c1_proved: bool
    exact_stimulus_variational_system_proved: bool
    stimulus_voltage_variation_strictly_positive_proved: bool
    stimulus_recovery_variation_strictly_positive_proved: bool
    terminal_history_curve_injective_proved: bool
    terminal_history_curve_oriented_c1_embedding_proved: bool
    componentwise_terminal_history_ordering_proved: bool
    inner_periodic_orbit_stable_manifold_validated: bool
    stable_manifold_defining_covector_validated: bool
    stable_covector_terminal_tangent_pairing_nonzero_validated: bool
    history_space_separator_and_routing_validated: bool
    endpoint_basin_inclusions_validated: bool
    unique_physical_pulse_onset_validated: bool
    canard_root_equals_physical_onset_proved: bool


def _fraction(value: Fraction) -> sp.Rational:
    return sp.Rational(value.numerator, value.denominator)


@lru_cache(maxsize=1)
def exact_pulse_reduction_defects() -> tuple[Any, ...]:
    """Return exact zero defects for the pulse ODE and its J variation."""

    voltage, recovery = sp.symbols("v w", real=True)
    p_voltage, p_recovery = sp.symbols("p_v p_w", real=True)
    alpha, stimulus = sp.symbols("alpha J", real=True)
    epsilon = _fraction(EPSILON)
    unfolding = _fraction(UNFOLDING)
    kappa_1 = _fraction(KAPPA_1)
    kappa_3 = _fraction(KAPPA_3)

    rfde_fast_with_equilibrium_slots = (
        voltage
        - voltage**3 / 3
        - recovery
        + epsilon * kappa_1 * (alpha - voltage)
        + epsilon
        * kappa_3
        * ((alpha - 1) ** 3 - (voltage - 1) ** 3)
        + stimulus
    )
    rfde_slow = epsilon * (voltage - unfolding - recovery)
    coefficient = (
        1
        - voltage**2
        - epsilon * kappa_1
        - 3 * epsilon * kappa_3 * (voltage - 1) ** 2
    )
    expected_p_fast = coefficient * p_voltage - p_recovery + 1
    expected_p_slow = epsilon * (p_voltage - p_recovery)
    differentiated_p_fast = (
        sp.diff(rfde_fast_with_equilibrium_slots, voltage) * p_voltage
        + sp.diff(rfde_fast_with_equilibrium_slots, recovery) * p_recovery
        + sp.diff(rfde_fast_with_equilibrium_slots, stimulus)
    )
    differentiated_p_slow = (
        sp.diff(rfde_slow, voltage) * p_voltage
        + sp.diff(rfde_slow, recovery) * p_recovery
        + sp.diff(rfde_slow, stimulus)
    )
    equilibrium_recovery = alpha - unfolding
    equilibrium_fast = rfde_fast_with_equilibrium_slots.subs(
        {
            voltage: alpha,
            recovery: equilibrium_recovery,
            stimulus: 0,
        }
    ).subs(unfolding, alpha**3 / 3)
    equilibrium_slow = rfde_slow.subs(
        {voltage: alpha, recovery: equilibrium_recovery}
    )
    return tuple(
        sp.simplify(value)
        for value in (
            differentiated_p_fast - expected_p_fast,
            differentiated_p_slow - expected_p_slow,
            equilibrium_fast,
            equilibrium_slow,
            coefficient
            - (
                1
                - voltage**2
                - epsilon * kappa_1
                - 3 * epsilon * kappa_3 * (voltage - 1) ** 2
            ),
        )
    )


def build_pulse_terminal_history_certificate() -> PulseTerminalHistoryCertificate:
    """Build the exact terminal-history and orientation certificate."""

    if exact_pulse_reduction_defects() != (0, 0, 0, 0, 0):
        raise AssertionError("the pulse ODE or stimulus variation changed")
    # Squaring is valid because every quantity is positive.
    if not all(multiplier * multiplier * 5 > 1 for multiplier in DELAY_MULTIPLIERS):
        raise AssertionError("a declared physical delay entered the pulse window")
    return PulseTerminalHistoryCertificate(
        model_id=MODEL_ID,
        audit_id=AUDIT_ID,
        history_space="X=C([-5*sqrt(5),0],R^2)",
        epsilon="1/5",
        unfolding_a="1/4",
        kappa_1="1/250",
        kappa_3="1/200",
        pulse_interval=("0", "1"),
        declared_pulse_amplitude_interval=("3/10", "8/25"),
        physical_delays=("4*sqrt(5)", "5*sqrt(5)"),
        delayed_slot_during_pulse=(
            "the quiet equilibrium (alpha,alpha-a) in both delay slots"
        ),
        reduced_fast_equation=(
            "v'=v-v^3/3-w+(1/5)(1/250)(alpha-v)+"
            "(1/5)(1/200)((alpha-1)^3-(v-1)^3)+J"
        ),
        reduced_slow_equation="w'=(1/5)(v-1/4-w)",
        voltage_stimulus_variation_equation="p'=A(v)p-q+1",
        recovery_stimulus_variation_equation="q'=(1/5)(p-q)",
        current_variational_coefficient=(
            "A(v)=1-v^2-(1/5)(1/250)-3(1/5)(1/200)(v-1)^2<=1"
        ),
        voltage_variation_upper_bound="0<p(t)<exp(t)-1<2 for 0<t<=1",
        recovery_variation_upper_bound="0<q(t)<2/5 for 0<t<=1",
        first_zero_derivative_lower_bound="p'(t_*)=1-q(t_*)>3/5",
        terminal_history_derivative=(
            "D_J K(J)(theta)=0 for theta in [-5*sqrt(5),-1] and "
            "=(p(1+theta),q(1+theta)) for theta in [-1,0]"
        ),
        exact_scope=(
            "joint C1 regularity and positive J-orientation of the physical "
            "terminal-history curve in the RFDE phase space"
        ),
        remaining_transversality=(
            "validate a stable-manifold defining covector ell and prove "
            "ell[D_J K(J_c)] is nonzero with the routed orientation"
        ),
        **{name: True for name in EXACT_TRUE_FLAGS},
        **{name: False for name in OPEN_FALSE_FLAGS},
    )


def json_ready_pulse_terminal_history_audit() -> dict[str, object]:
    certificate = asdict(build_pulse_terminal_history_certificate())
    return {"certificate": json.loads(json.dumps(certificate))}


def validate_pulse_terminal_history_audit(payload: Mapping[str, Any]) -> None:
    if not isinstance(payload, Mapping) or set(payload) != {"certificate"}:
        raise ValueError("pulse terminal audit must contain one certificate")
    certificate = payload.get("certificate")
    if not isinstance(certificate, Mapping):
        raise ValueError("pulse terminal certificate must be a mapping")
    expected_fields = {field.name for field in fields(PulseTerminalHistoryCertificate)}
    if set(certificate) != expected_fields:
        raise ValueError("pulse terminal certificate schema changed")
    reference = json.loads(
        json.dumps(asdict(build_pulse_terminal_history_certificate()))
    )
    if dict(certificate) != reference:
        raise ValueError("pulse terminal certificate differs from exact reference")
    if any(certificate.get(name) is not True for name in EXACT_TRUE_FLAGS):
        raise ValueError("an exact terminal-history conclusion was weakened")
    if any(certificate.get(name) is not False for name in OPEN_FALSE_FLAGS):
        raise ValueError("an open onset or separator conclusion was promoted")


def _sha256_path(path: Path) -> str:
    return sha256(path.read_bytes()).hexdigest()


def validate_pulse_terminal_history_result(
    payload: Mapping[str, Any], repository: Path
) -> None:
    if not isinstance(payload, Mapping) or set(payload) != {"audit", "manifest"}:
        raise ValueError("pulse terminal result requires audit and manifest")
    audit = payload.get("audit")
    manifest = payload.get("manifest")
    if not isinstance(audit, Mapping) or not isinstance(manifest, Mapping):
        raise ValueError("pulse terminal result records must be mappings")
    validate_pulse_terminal_history_audit(audit)
    sources = {
        "proof_source": PROOF_SOURCE_RELATIVE_PATH,
        "parent_source": PARENT_SOURCE_RELATIVE_PATH,
        "parent_probe": PARENT_PROBE_RELATIVE_PATH,
        "generator": GENERATOR_RELATIVE_PATH,
        "note": NOTE_RELATIVE_PATH,
    }
    expected_keys = {
        "model_id",
        "audit_id",
        "default_command",
        "arithmetic",
        "python",
        "platform",
        "sympy",
        *(sources.keys()),
        *(f"{name}_sha256" for name in sources),
    }
    if set(manifest) != expected_keys:
        raise ValueError("pulse terminal manifest schema changed")
    scalar_expected = {
        "model_id": MODEL_ID,
        "audit_id": AUDIT_ID,
        "default_command": DEFAULT_COMMAND,
        "arithmetic": MANIFEST_ARITHMETIC,
        "python": platform.python_version(),
        "platform": platform.platform(),
        "sympy": sp.__version__,
    }
    for name, expected in scalar_expected.items():
        if manifest.get(name) != expected:
            raise ValueError(f"pulse terminal manifest {name} changed")
    for name, relative in sources.items():
        if manifest.get(name) != relative:
            raise ValueError(f"pulse terminal manifest {name} path changed")
        if manifest.get(f"{name}_sha256") != _sha256_path(repository / relative):
            raise ValueError(f"pulse terminal manifest {name} hash changed")


__all__ = [
    "AUDIT_ID",
    "DEFAULT_COMMAND",
    "EXACT_TRUE_FLAGS",
    "GENERATOR_RELATIVE_PATH",
    "MANIFEST_ARITHMETIC",
    "MODEL_ID",
    "NOTE_RELATIVE_PATH",
    "OPEN_FALSE_FLAGS",
    "PARENT_PROBE_RELATIVE_PATH",
    "PARENT_SOURCE_RELATIVE_PATH",
    "PROOF_SOURCE_RELATIVE_PATH",
    "PulseTerminalHistoryCertificate",
    "RESULT_RELATIVE_PATH",
    "build_pulse_terminal_history_certificate",
    "exact_pulse_reduction_defects",
    "json_ready_pulse_terminal_history_audit",
    "validate_pulse_terminal_history_audit",
    "validate_pulse_terminal_history_result",
]
